env:
  maze_size: 9
  num_maze: -1
  max_episode_steps: 500
  target_reward: 1.0
  per_step_reward: 0.0
  num_labels: 16
  render_mode: null
  no_duplication: True
  seed: 10
  maps: null
  n_envs: 1
  epn: True
  norm_reward: True
  norm_obs: True

ppo:
  batch_size: 64
  n_steps: 64
  n_epochs: 5
  gamma: 0.995
  gae_lambda: 0.95
  max_grad_norm: 1
  ent_coef: 0.001
  normalize_advantage: True
  verbose: 1

epn:
  embedding_size: 32
  num_heads: 1
  hidden_size: 128
  num_iterations: 2

optim:
  total_timesteps: 500_000_000
  linear_schedule: False
  learning_rate: 0.0003
  clip_range: 0.2

logger:
  upload_to_wandb: False
  run_dir:
  proj_name:
  group_name: EPN

seed: 10
